@startuml
object user {
    id
    name
    mobile
    '关注
    follow
    '粉丝
    fans
}

object post {
    id
    user
    title
    content
}

object comment {
    id
    user
    post
    '回复的评论
    comment
}
@enduml